config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token
from portfolio.blog.feeds import LatestPostsFeed

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path("markdownx/", include("markdownx.urls")),
    path("", include("portfolio.core.urls")),
    path("projects/", include("portfolio.projects.urls", namespace="projects")),
    path("blog/", include("portfolio.blog.urls", namespace="blog")),
    path("feed/rss/", LatestPostsFeed(), name="post_feed"),
    path("newsletter/", include("portfolio.newsletter.urls", namespace="newsletter")),
    path("maintenance-mode/", include("maintenance_mode.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/blog/urls.py
from django.urls import path

from .views import (
    NewPostView,
    PublishPostView,
    PostCreateView,
    PostContentEditorView,
    PostListView,
    PostDetailView,
    SecretKeyPostDetailView,
    PostDeleteView,
    PostUpdateView,
    SeriesListView,
    SeriesCreateView,
    SeriesDetailView,
    SeriesUpdateView,
    SeriesDeleteView,
    TagListView,
)

app_name = "blog"
urlpatterns = [
    path("new-post/", NewPostView.as_view(), name="new_post"),
    path("post-publish/<str:slug>/", PublishPostView.as_view(), name="post_publish"),
    path("post-list/", PostListView.as_view(), name="post_list"),
    path("post-list/<str:tag>/", PostListView.as_view(), name="post_list_filtered"),
    path("post-create/", PostCreateView.as_view(), name="post_create"),
    path(
        "post-content-editor/<str:slug>/",
        PostContentEditorView.as_view(),
        name="post_content_editor",
    ),
    path("post-detail/<str:slug>/", PostDetailView.as_view(), name="post_detail",),
    path(
        "post-secret/<str:secret_key>/",
        SecretKeyPostDetailView.as_view(),
        name="secret_post_detail",
    ),
    path("post-update/<str:slug>/", PostUpdateView.as_view(), name="post_update",),
    path("post-delete/<str:slug>/", PostDeleteView.as_view(), name="post_delete",),
    path("series-list/", SeriesListView.as_view(), name="series_list",),
    path("series-create/", SeriesCreateView.as_view(), name="series_create",),
    path(
        "series-detail/<str:slug>/", SeriesDetailView.as_view(), name="series_detail",
    ),
    path(
        "series-update/<str:slug>/", SeriesUpdateView.as_view(), name="series_update",
    ),
    path(
        "series-delete/<str:slug>/", SeriesDeleteView.as_view(), name="series_delete",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
]

portfolio/core/urls.py
from django.urls import path

from .views import home, GetInTouchView

urlpatterns = [
    path("", home, name="home"),
    path("get-in-touch/", GetInTouchView.as_view(), name="contact_me"),
]

portfolio/newsletter/urls.py
from django.urls import path

from .views import (
    SubscriptionView,
    SubscribeConfirmView,
    UnsubscribeView,
    SendNews,
    UnsubscribeConfirmView,
    SendUnsubscribeLinkView,
)

app_name = "newsletter"
urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path(
        "subscribe-confirm/<str:uuid>/",
        SubscribeConfirmView.as_view(),
        name="subscribe_confirm",
    ),
    path("unsubscribe/<str:uuid>/", UnsubscribeView.as_view(), name="unsubscribe"),
    path(
        "unsubscribe-confirm/",
        UnsubscribeConfirmView.as_view(),
        name="unsubscribe_confirm",
    ),
    path(
        "unsubscribe-test/", SendUnsubscribeLinkView.as_view(), name="unsubscribe_test",
    ),
    path("send-news/", SendNews.as_view(), name="send_news"),
]

portfolio/projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("project-create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project-details/<str:slug>/",
        ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project-update/<str:slug>/", ProjectUpdateView.as_view(), name="project_update"
    ),
    path(
        "project-delete/<str:slug>/", ProjectDeleteView.as_view(), name="project_delete"
    ),
]

portfolio/projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "carousel",
            "title",
            "description",
            "status",
            "what_ive_learned",
            "tech_stack",
            "featured",
            "priority",
            "github_link",
            "web_link",
        ]

portfolio/blog/views.py
from braces.views import SuperuserRequiredMixin, FormValidMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from taggit.models import Tag

from portfolio.newsletter.forms import SubscriptionForm
from .forms import BlogPostContentForm, PostForm, SeriesForm
from .helpers import postable_add_extra_context, post_filter
from .models import Post, Series


class NewPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/new_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        drafts = Post.objects.filter(status=Post.STATUS.draft).order_by(
            "-modified", "-created"
        )
        paginator = Paginator(drafts, 6)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class PublishPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/post_confirm_publish.html"

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        post.publish()
        messages.success(request, "Post published")
        return redirect("blog:post_list")


class PostListView(ListView):
    context_object_name = "posts"
    paginate_by = 8

    def get_queryset(self):
        queryset = Post.objects.filter(status=Post.STATUS.published).order_by(
            "-publish_date"
        )
        filtered_post = post_filter(
            self.request, tag=self.kwargs.get("tag"), queryset=queryset
        )
        return filtered_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class PostCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    model = Post
    template_name = "blog/post_create.html"
    form_class = PostForm
    form_valid_message = "Blog post created"

    def get_success_url(self) -> str:
        post = self.get_context_data().get("post")
        return reverse("blog:post_content_editor", kwargs={"slug": post.slug})


class PostContentEditorView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(initial={"body": post.body})
        return render(
            request, "blog/post_content_editor.html", {"form": form, "slug": post.slug},
        )

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(request.POST)
        if form.is_valid():
            post.body = form.cleaned_data["body"]
            post.save()
            messages.success(request, "Post Updated")
            return redirect("blog:post_detail", slug=post.slug)
        else:
            return redirect("blog:post_content_editor", kwargs={"slug": post})


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_published and not self.request.user.is_superuser:  # noqa
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SecretKeyPostDetailView(DetailView):
    model = Post
    slug_url_kwarg = "secret_key"
    slug_field = "secret_key"
    template_name = "blog/post_detail.html"

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.is_published:  # noqa
            return redirect(post.get_absolute_url())  # noqa
        return super().get(request, *args, **kwargs)


class PostUpdateView(
    SuperuserRequiredMixin, FormValidMessageMixin, UpdateView,
):
    model = Post
    template_name = "blog/post_update.html"
    form_class = PostForm
    form_valid_message = "Blog post updated"


class PostDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Post
    form_valid_message = "Blog post deleted"

    def get_success_url(self) -> str:
        return reverse("blog:post_list")


class SeriesCreateView(CreateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_create.html"


class SeriesListView(ListView):
    queryset = Series.objects.filter(visible=True).order_by("created")
    paginate_by = 8
    context_object_name = "series"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class SeriesDetailView(DetailView):
    model = Series

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SeriesUpdateView(SuperuserRequiredMixin, FormValidMessageMixin, UpdateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_update.html"
    form_valid_message = "Blog Series Updated"


class SeriesDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Series
    form_valid_message = "Blogpost Series Deleted"

    def get_success_url(self):
        return reverse("blog:series_list")


class TagListView(ListView):
    queryset = Tag.objects.all()
    template_name = "blog/tag_list.html"
    context_object_name = "tags"

portfolio/core/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import FormView
from django_q.tasks import async_task

from portfolio.projects.models import Project
from .forms import GetInTouchForm

DEFAULT_FROM_EMAIL = getattr(settings, "DEFAULT_FROM_EMAIL", "contact@tobidegnon.com")


def home(request):
    featured = Project.objects.filter(featured=True).order_by("-priority", "-created")[
        :3
    ]
    return render(request, "core/home.html", {"featured": featured})


# TODO write a telegram bot that send message whenever a message is sent
class GetInTouchView(FormView):
    form_class = GetInTouchForm
    template_name = "core/get_in_touch.html"

    def form_valid(self, form):
        message = (
            f"Full Name: {form.cleaned_data['full_name']}\n"
            f"Email: {form.cleaned_data['email']}\n\n"
            f"{form.cleaned_data['message']}"
        )
        async_task(
            send_mail,
            subject=form.cleaned_data["subject"],
            message=message,
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=["tobidegnon@protonmail.com", "degnonfrancis@gmail.com",],
        )
        messages.success(
            self.request, "Thanks for your message, I will be reaching you soon !"
        )

        return render(
            self.request, "core/get_in_touch.html", {"form": GetInTouchForm()}
        )

portfolio/newsletter/views.py
from braces.views import SuperuserRequiredMixin
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, FormView, TemplateView
from django_q.tasks import async_task

from .forms import SubscriptionForm, NewsForm, UnsubscriptionForm, EmailForm
from .models import Subscriber


class SubscriptionView(View):
    def get(self, request, *args, **kwargs):  # noqa
        form = SubscriptionForm()
        context = {"form": form, "is_valid": False}
        return render(request, "newsletter/subscribe.html", context=context)

    def post(self, request, *args, **kwargs):  # noqa
        form = SubscriptionForm(request.POST)
        context = {"is_valid": False}
        if form.is_valid():
            Subscriber.add_subscriber(email=form.cleaned_data["email"])
            context["is_valid"] = True
        form = SubscriptionForm()
        context["form"] = form
        return render(request, "newsletter/subscribe.html", context=context)


class SubscribeConfirmView(View):
    """View called when user click on the confirmation link he received by mail"""

    def get(self, request, *args, **kwargs):  # noqa
        submission = get_object_or_404(Subscriber, uuid=kwargs["uuid"])
        submission.confirm()
        return render(request, "newsletter/subscribe_confirm.html")


class UnsubscribeView(FormView):
    """View called when a user clik on his unsubscribe link"""

    template_name = "newsletter/unsubscribe.html"
    form_class = UnsubscriptionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["obj"] = get_object_or_404(Subscriber, uuid=self.kwargs.get("uuid"))
        return context

    def form_valid(self, form):
        async_task(
            Subscriber.remove_subscriber,
            sub_obj=self.get_context_data().get("obj"),
            **form.cleaned_data,
        )
        return redirect("newsletter:unsubscribe_confirm")


class UnsubscribeConfirmView(TemplateView):
    template_name = "newsletter/unsubscribe_confirm.html"


class SendUnsubscribeLinkView(SuperuserRequiredMixin, View):
    """THis views is only for testing purpose, test if the unbubscribe link
        is really sent
    """

    def get(self, request, *args, **kwargs):  # noqa
        return render(
            request, "newsletter/unsubscribe_test.html", context={"form": EmailForm()}
        )

    def post(self, request, *args, **kwargs):  # noqa
        form = EmailForm(request.POST)
        if form.is_valid():
            sub = Subscriber.objects.create(
                email=form.cleaned_data["email"], confirmed=True
            )
            sub.send_unsubscription_link()
            messages.success(request, "Link Sent")
        return render(
            request, "newsletter/unsubscribe_test.html", context={"form": form}
        )


class SendNews(SuperuserRequiredMixin, FormView):
    template_name = "newsletter/send_news.html"
    form_class = NewsForm

    def form_valid(self, form):
        form.save().setup()
        messages.success(self.request, "Sending...")
        return render(
            self.request, "newsletter/send_news.html", context={"form": NewsForm()}
        )

portfolio/projects/views.py
from braces.views import FormValidMessageMixin, SuperuserRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from .forms import ProjectForm
from .models import Project


class ProjectListView(ListView):
    model = Project
    ordering = ["-priority", "-created"]
    paginate_by = 6
    context_object_name = "projects"


class ProjectDetailView(DetailView):
    model = Project


class ProjectCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    form_class = ProjectForm
    form_valid_message = "Project Created"
    template_name = "projects/project_create.html"


class ProjectUpdateView(FormValidMessageMixin, SuperuserRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_update.html"
    form_valid_message = "Project Updated"


class ProjectDeleteView(FormValidMessageMixin, SuperuserRequiredMixin, DeleteView):
    model = Project
    form_valid_message = "Project deleted"

    def get_success_url(self) -> str:
        return reverse("projects:project_list")

portfolio/templates/503.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Site Maintenance</title>
  <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
  />
</head>
<body class="bg-dark">
<div class="container">
  <div class="card mt-4">
    <div class="card-header">
      <h3 class="text-big text-bold text-center">Maintenance!!!</h3>
    </div>
    <div class="card-body">
      <p class="text-big text-bold">
        Sorry, site under maintenance right now, you can still contact me through these links if needed.
      </p>
      <div class="btn-group" role="group">
        <a href="{{ github }}" class="btn"
        ><img
                alt="tobi-de | Github"
                width="22px"
                src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/github.svg"
        /></a>
        <a href="mailto:{{ email }}" class="btn"
        ><img
                alt="tobi-de | Gmail"
                width="22px"
                src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/gmail.svg"
        /></a>
        <a href="{{ telegram }}" class="btn"
        ><img
                alt="tobi-de | Telegram"
                width="22px"
                src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/telegram.svg"
        /></a>
        <a href="{{ twitter }}" class="btn"
        ><img
                alt="tobi-de | Twitter"
                width="22px"
                src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/twitter.svg"
        /></a>
      </div>
    </div>
  </div>
</div>
</body>
</html>

portfolio/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Tobi-De{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
        content="{% block description %}Full Stack Web Development with Django, blog post and more.{% endblock description %}">
  <meta name="author" content="Tobi DEGNON">
  <meta name="og:site_name" content="Tobi-De"/>
  <meta name="twitter:card" content="summary_large_image">
  {% block extra_meta %}
    <meta property="og:image" content="{% static "images/dt150.png" %}"/>
    <meta name="twitter:image" content="{% static "images/dt150.png" %}">
    <meta property="og:image:width" content="150"/>
    <meta property="og:image:height" content="119"/>
    <meta property="og:image:alt" content="Tobi-De Django Freelancer"/>
  {% endblock extra_meta %}


  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}

    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/markdown.css' %}">
    <link rel="stylesheet" href="{% static code_theme_path %}">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
  {% endblock %}

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169302163-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-169302163-1');
  </script>
  <!-- GOOGLE ANALYTICS -->
</head>

<body class="bg-dark">

<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg" style="background-color: #fff">
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <a href="{% url "home" %}" class="navbar-brand">
          <img src="{% static "images/dt150.png" %}"
               alt="DEGNON tobi profile"
               class="img-fluid rounded-circle"
               style="width: 70px; height: 70px">
          <span class="text-big"><b>Tobi-De(Web Dev)</b></span>
        </a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse"
                aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler">
          <span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url "projects:project_list" %}" class="nav-link text-big">
              Projects<i class="fa fa-folder-open" style="margin-left: 3px"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url "blog:post_list" %}" class="nav-link text-big">
              Blog<i class="fa fa-book" style="margin-left: 3px"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url "post_feed" %}" class="nav-link text-big">
              RSS
              <i class="fa fa-rss" style="margin-right: 3px"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url "contact_me" %}" class="nav-link text-big">Get in touch
              <i class="fa fa-address-book" style="margin-left: 3px"></i>
            </a>
          </li>
          {% if user.is_superuser %}
            <div class="dropdown">
              <button class="btn btn-outline-dark btn-sm dropdown-toggle mt-2" type="button" id="AdminMenuButton"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin
              </button>
              <div class="dropdown-menu" aria-labelledby="AdminMenuButton">
                <a href="{% url "admin:index" %}" class="dropdown-item">
                  Home<i class="fa fa-lock" style="margin-left: 3px"></i></a>
                <a href="{% url "blog:new_post" %}" class="dropdown-item">
                  New<i class="fa fa-plus-square" style="margin-left: 3px"></i></a>
                <a href="{% url "newsletter:send_news" %}" class="dropdown-item">
                  Send News<i class="fa fa-paper-plane" style="margin-left: 3px"></i></a>
                {% if maintenance_mode %}
                  <a href="{% url "maintenance_mode_off" %}" class="dropdown-item">
                    Maintenance<i class="fa fa-toggle-on" style="margin-left: 3px"></i></a>
                {% else %}
                  <a href="{% url "maintenance_mode_on" %}" class="dropdown-item">
                    Maintenance<i class="fa fa-toggle-off" style="margin-left: 3px"></i></a>
                {% endif %}
              </div>
            </div>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

<div class="container">
  <div class="row justify-content-center">
    {% if messages %}
      {% for message in messages %}
        <div class="col-md-10 alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                  aria-hidden="true">&times;</span></button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% block content %}
{% endblock content %}

{% block modal %}{% endblock modal %}

<!-- Page Footer-->
<footer class="site-footer">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-3">
        <p>©&nbsp;2020 · <a href="https://www.tobidegnon.com">Tobi-De</a></p>
      </div>
      <div class="col-md-3">
        <a href="http://www.djangoproject.com/"><img
                src="https://www.djangoproject.com/m/img/badges/djangomade124x25_grey.gif" border="0"
                alt="Made with Django." title="Made with Django."/></a>
      </div>

    </div>
  </div>

</footer>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
  <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/front.js' %}"></script>
{% endblock javascript %}
</body>
</html>

portfolio/templates/newsletter.html
{% load crispy_forms_tags %}
<div class="rounded card-body bg-white">
  <p><b>Subscribe to get notified about new posts about python, django and programming in
    general.</b></p>
  <form method="post" action="{% url "newsletter:subscribe" %}">
    {% csrf_token %}
    {{ n_form | crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

portfolio/templates/sidebar_left.html
{% load blog_tags %}
<aside class="col-md-3">
  <div class="widget">
    <header>
      <h3 class="h6">Coming Soon</h3>
    </header>
    <div class="blog-posts">
      {% for post in coming_soon %}
        <div class="item d-flex align-items-center">
          <div class="title mb-2">{{ post.title }}</div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="widget categories">
    <header>
      <h3 class="h6">Tags</h3>
    </header>
    {% for tag in tags %}
      <div class="item d-flex justify-content-between"><a
              href="{% url "blog:post_list_filtered" tag %}">#{{ tag }}</a><span> {{ tag|tag_post_count }}</span>
      </div>
    {% endfor %}
    <a class="a-title row justify-content-center" href="{% url "blog:tag_list" %}">All tags</a>
  </div>
</aside>