config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token
from portfolio.blog.feeds import LatestPostsFeed

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path("markdownx/", include("markdownx.urls")),
    path("", include("portfolio.core.urls")),
    path("projects/", include("portfolio.projects.urls", namespace="projects")),
    path("blog/", include("portfolio.blog.urls", namespace="blog")),
    path("feed/rss/", LatestPostsFeed(), name="post_feed"),
    path("newsletter/", include("portfolio.newsletter.urls", namespace="newsletter")),
    path("maintenance-mode/", include("maintenance_mode.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/blog/urls.py
from django.urls import path

from .views import (
    NewPostView,
    PublishPostView,
    PostCreateView,
    PostContentEditorView,
    PostListView,
    PostDetailView,
    SecretKeyPostDetailView,
    PostDeleteView,
    PostUpdateView,
    SeriesListView,
    SeriesCreateView,
    SeriesDetailView,
    SeriesUpdateView,
    SeriesDeleteView,
    TagListView,
)

app_name = "blog"
urlpatterns = [
    path("new-post/", NewPostView.as_view(), name="new_post"),
    path("post-publish/<str:slug>/", PublishPostView.as_view(), name="post_publish"),
    path("post-list/", PostListView.as_view(), name="post_list"),
    path("post-list/<str:tag>/", PostListView.as_view(), name="post_list_filtered"),
    path("post-create/", PostCreateView.as_view(), name="post_create"),
    path(
        "post-content-editor/<str:slug>/",
        PostContentEditorView.as_view(),
        name="post_content_editor",
    ),
    path("post-detail/<str:slug>/", PostDetailView.as_view(), name="post_detail",),
    path(
        "post-secret/<str:secret_key>/",
        SecretKeyPostDetailView.as_view(),
        name="secret_post_detail",
    ),
    path("post-update/<str:slug>/", PostUpdateView.as_view(), name="post_update",),
    path("post-delete/<str:slug>/", PostDeleteView.as_view(), name="post_delete",),
    path("series-list/", SeriesListView.as_view(), name="series_list",),
    path("series-create/", SeriesCreateView.as_view(), name="series_create",),
    path(
        "series-detail/<str:slug>/", SeriesDetailView.as_view(), name="series_detail",
    ),
    path(
        "series-update/<str:slug>/", SeriesUpdateView.as_view(), name="series_update",
    ),
    path(
        "series-delete/<str:slug>/", SeriesDeleteView.as_view(), name="series_delete",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
]

portfolio/core/urls.py
from django.urls import path

from .views import home, GetInTouchView

urlpatterns = [
    path("", home, name="home"),
    path("get-in-touch/", GetInTouchView.as_view(), name="contact_me"),
]

portfolio/projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("project-create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project-details/<str:slug>/",
        ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project-update/<str:slug>/", ProjectUpdateView.as_view(), name="project_update"
    ),
    path(
        "project-delete/<str:slug>/", ProjectDeleteView.as_view(), name="project_delete"
    ),
]

portfolio/blog/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from .models import Post, Series


class BlogPostContentForm(forms.Form):
    body = MarkdownxFormField(label="")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "thumbnail",
            "title",
            "overview",
            "status",
            "tags",
            "series",
            "featured",
            "scheduled_publish_date",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["overview"].label = ""


class SeriesForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ["thumbnail", "title", "overview", "body", "status"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["overview"].label = ""
        self.fields["body"].label = ""

portfolio/blog/views.py
from braces.views import SuperuserRequiredMixin, FormValidMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from taggit.models import Tag

from portfolio.newsletter.forms import SubscriptionForm
from .forms import BlogPostContentForm, PostForm, SeriesForm
from .helpers import postable_add_extra_context, post_filter
from .models import Post, Series


class NewPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/new_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        drafts = Post.objects.filter(status=Post.STATUS.draft).order_by(
            "-modified", "-created"
        )
        paginator = Paginator(drafts, 6)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class PublishPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/post_confirm_publish.html"

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        post.publish()
        messages.success(request, "Post published")
        return redirect("blog:post_list")


class PostListView(ListView):
    context_object_name = "posts"
    paginate_by = 8

    def get_queryset(self):
        queryset = Post.objects.filter(status=Post.STATUS.published).order_by(
            "-publish_date"
        )
        filtered_post = post_filter(
            self.request, tag=self.kwargs.get("tag"), queryset=queryset
        )
        return filtered_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class PostCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    model = Post
    template_name = "blog/post_create.html"
    form_class = PostForm
    form_valid_message = "Blog post created"

    def get_success_url(self) -> str:
        post = self.get_context_data().get("post")
        return reverse("blog:post_content_editor", kwargs={"slug": post.slug})


class PostContentEditorView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(initial={"body": post.body})
        return render(
            request, "blog/post_content_editor.html", {"form": form, "slug": post.slug},
        )

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(request.POST)
        if form.is_valid():
            post.body = form.cleaned_data["body"]
            post.save()
            messages.success(request, "Post Updated")
            return redirect("blog:post_detail", slug=post.slug)
        else:
            return redirect("blog:post_content_editor", kwargs={"slug": post})


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_published and not self.request.user.is_superuser:  # noqa
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SecretKeyPostDetailView(DetailView):
    model = Post
    slug_url_kwarg = "secret_key"
    slug_field = "secret_key"
    template_name = "blog/post_detail.html"

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.is_published:  # noqa
            return redirect(post.get_absolute_url())  # noqa
        return super().get(request, *args, **kwargs)


class PostUpdateView(
    SuperuserRequiredMixin, FormValidMessageMixin, UpdateView,
):
    model = Post
    template_name = "blog/post_update.html"
    form_class = PostForm
    form_valid_message = "Blog post updated"


class PostDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Post
    form_valid_message = "Blog post deleted"

    def get_success_url(self) -> str:
        return reverse("blog:post_list")


class SeriesCreateView(CreateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_create.html"


class SeriesListView(ListView):
    queryset = Series.objects.filter(visible=True).order_by("created")
    paginate_by = 8
    context_object_name = "series"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class SeriesDetailView(DetailView):
    model = Series

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SeriesUpdateView(SuperuserRequiredMixin, FormValidMessageMixin, UpdateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_update.html"
    form_valid_message = "Blog Series Updated"


class SeriesDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Series
    form_valid_message = "Blogpost Series Deleted"

    def get_success_url(self):
        return reverse("blog:series_list")


class TagListView(ListView):
    queryset = Tag.objects.all()
    template_name = "blog/tag_list.html"
    context_object_name = "tags"

portfolio/core/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import FormView
from django_q.tasks import async_task

from portfolio.projects.models import Project
from .forms import GetInTouchForm

DEFAULT_FROM_EMAIL = getattr(settings, "DEFAULT_FROM_EMAIL", "contact@tobidegnon.com")


def home(request):
    featured = Project.objects.filter(featured=True).order_by("-priority", "-created")[
        :3
    ]
    return render(request, "core/home.html", {"featured": featured})


# TODO write a telegram bot that send message whenever a message is sent
class GetInTouchView(FormView):
    form_class = GetInTouchForm
    template_name = "core/get_in_touch.html"

    def form_valid(self, form):
        message = (
            f"Full Name: {form.cleaned_data['full_name']}\n"
            f"Email: {form.cleaned_data['email']}\n\n"
            f"{form.cleaned_data['message']}"
        )
        async_task(
            send_mail,
            subject=form.cleaned_data["subject"],
            message=message,
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=["tobidegnon@protonmail.com", "degnonfrancis@gmail.com",],
        )
        messages.success(
            self.request, "Thanks for your message, I will be reaching you soon !"
        )

        return render(
            self.request, "core/get_in_touch.html", {"form": GetInTouchForm()}
        )

portfolio/newsletter/views.py
from braces.views import SuperuserRequiredMixin
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, FormView, TemplateView
from django_q.tasks import async_task

from .forms import SubscriptionForm, NewsForm, UnsubscriptionForm, EmailForm
from .models import Subscriber


class SubscriptionView(View):
    def get(self, request, *args, **kwargs):  # noqa
        form = SubscriptionForm()
        context = {"form": form, "is_valid": False}
        return render(request, "newsletter/subscribe.html", context=context)

    def post(self, request, *args, **kwargs):  # noqa
        form = SubscriptionForm(request.POST)
        context = {"is_valid": False}
        if form.is_valid():
            Subscriber.add_subscriber(email=form.cleaned_data["email"])
            context["is_valid"] = True
        form = SubscriptionForm()
        context["form"] = form
        return render(request, "newsletter/subscribe.html", context=context)


class SubscribeConfirmView(View):
    """View called when user click on the confirmation link he received by mail"""

    def get(self, request, *args, **kwargs):  # noqa
        submission = get_object_or_404(Subscriber, uuid=kwargs["uuid"])
        submission.confirm()
        return render(request, "newsletter/subscribe_confirm.html")


class UnsubscribeView(FormView):
    """View called when a user clik on his unsubscribe link"""

    template_name = "newsletter/unsubscribe.html"
    form_class = UnsubscriptionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["obj"] = get_object_or_404(Subscriber, uuid=self.kwargs.get("uuid"))
        return context

    def form_valid(self, form):
        async_task(
            Subscriber.remove_subscriber,
            sub_obj=self.get_context_data().get("obj"),
            **form.cleaned_data,
        )
        return redirect("newsletter:unsubscribe_confirm")


class UnsubscribeConfirmView(TemplateView):
    template_name = "newsletter/unsubscribe_confirm.html"


class SendUnsubscribeLinkView(SuperuserRequiredMixin, View):
    """THis views is only for testing purpose, test if the unbubscribe link
        is really sent
    """

    def get(self, request, *args, **kwargs):  # noqa
        return render(
            request, "newsletter/unsubscribe_test.html", context={"form": EmailForm()}
        )

    def post(self, request, *args, **kwargs):  # noqa
        form = EmailForm(request.POST)
        if form.is_valid():
            sub = Subscriber.objects.create(
                email=form.cleaned_data["email"], confirmed=True
            )
            sub.send_unsubscription_link()
            messages.success(request, "Link Sent")
        return render(
            request, "newsletter/unsubscribe_test.html", context={"form": form}
        )


class SendNews(SuperuserRequiredMixin, FormView):
    template_name = "newsletter/send_news.html"
    form_class = NewsForm

    def form_valid(self, form):
        form.save().setup()
        messages.success(self.request, "Sending...")
        return render(
            self.request, "newsletter/send_news.html", context={"form": NewsForm()}
        )

portfolio/projects/views.py
from braces.views import FormValidMessageMixin, SuperuserRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from .forms import ProjectForm
from .models import Project


class ProjectListView(ListView):
    model = Project
    ordering = ["-priority", "-created"]
    paginate_by = 6
    context_object_name = "projects"


class ProjectDetailView(DetailView):
    model = Project


class ProjectCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    form_class = ProjectForm
    form_valid_message = "Project Created"
    template_name = "projects/project_create.html"


class ProjectUpdateView(FormValidMessageMixin, SuperuserRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_update.html"
    form_valid_message = "Project Updated"


class ProjectDeleteView(FormValidMessageMixin, SuperuserRequiredMixin, DeleteView):
    model = Project
    form_valid_message = "Project deleted"

    def get_success_url(self) -> str:
        return reverse("projects:project_list")

portfolio/templates/projects/project_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main>
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete this project ?</p>
            <input type="submit" class="btn btn-danger" value="confirm"/>
          </form>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/projects/project_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <form action="{% url "projects:project_create" %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form | crispy }}
              <button type="submit" class="btn btn-primary">Create</button>
            </form>
            {{ form.media }}
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/projects/project_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load core_tags %}

{% block  title %}{{ product.title }}{% endblock title %}
{% block  description %}{{ project.description|markdown|striptags|truncatewords:30 }}{% endblock description %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card border-0">
          <div id="carouselControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              {% for el in project.carousel.all %}
                {% thumbnail el.image "1000x450" as img %}
                  <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                    <img src="{{ img.url }}" class="d-block w-100 img-fluid" alt="{{ el.alt }}">
                  </div>
                {% endthumbnail %}
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="card-body">
            {% if user.is_superuser %}
              <div class="row justify-content-center mb-3">
                <div class="col-md-2">
                  <div class="btn-group btn-group-sm" role="group">
                    <a class="btn btn-info" href="{% url "projects:project_update" slug=project.slug %}">update</a>
                    <a class="btn btn-danger" href="{% url "projects:project_delete" slug=project.slug %}">delete</a>
                  </div>
                </div>
              </div>
            {% endif %}
            <h2 class="h2 text-center mb-4">{{ project.title.capitalize }}</h2>
            <div class="mb-4">
              <h6>Description</h6>
              <p class="text-justify">{{ project.description|markdown }}</p>
            </div>
            <div class="mb-4 mt-4">
              <h6>Technologies</h6>
              <div class="row btn-group mt-2 ml-1" role="group">
                {% for tech in project.tech_stack.all %}
                  <a type="button" class="btn btn-info text-white">{{ tech }}</a>
                {% endfor %}
              </div>
            </div>
            <div class="mb-4">
              <h6>What I've Learned</h6>
              <div>{{ project.what_ive_learned|markdown }}</div>
            </div>
            <div class="mb-4">
              {% if project.github_link or project.web_link %}
                <h6>External Links</h6>
                <div class="btn-group" role="group">
                  {% if  project.github_link %}
                    <a class="btn" href="{{ project.github_link }}" target="_blank"><span><i
                            class="fa fa-2x fa-github"></i></span></a>
                  {% endif %}
                  {% if  project.web_link %}
                    <a class="btn" href="{{ project.web_link }}" target="_blank"><span><i
                            class="fa fa-2x fa-globe"></i></span></a>
                  {% endif %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/projects/project_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load humanize %}
{% load core_tags %}

{% block content %}
  <section class="gallery-block cards-gallery">
    <div class="container">
      {% if user.is_superuser %}
        <div class="row justify-content-center">
          <a href="{% url "projects:project_create" %}" class="btn btn-primary mb-4 text-white">New</a>
        </div>
      {% endif %}
      <div class="row">
        {% for project in page_obj %}
          <div class="col-md-6 col-lg-4">
            <div class="card border-0 transform-on-hover">
              {% thumbnail project.primary_image.image "350x150" as img %}
                <a class="lightbox" href="{{ project.get_absolute_url }}">
                  <img src="{{ img.url }}" class="card-img-top" alt="{{ project.primary_image.alt }}">
                </a>
              {% endthumbnail %}
              <div class="card-body">
                <h5 class="card-title"><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h5>
                <p class="card-text text-justify">{{ project.overview|markdown }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <nav aria-label="Page navigation example">
        <ul class="pagination pagination-template d-flex justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i
                    class="fa fa-angle-left"></i></a></li>
            <li class="page-item"><a href="?page={{ page_obj.number|add:-1 }}"
                                     class="page-link">{{ page_obj.number|add:-1 }}</a></li>
          {% endif %}
          <li class="page-item"><a href="?page={{ page_obj.number }}"
                                   class="page-link active">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.number|add:1 }}"
                                     class="page-link">{{ page_obj.number|add:1 }}</a></li>
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> <i
                    class="fa fa-angle-right"></i></a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </section>
{% endblock %}

portfolio/templates/projects/project_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form | crispy }}
              <div class="form-group">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ project.get_absolute_url }}" class="btn btn-secondary">Back</a>
              </div>
            </form>
            {{ form.media }}
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}