config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token
from portfolio.blog.feeds import LatestPostsFeed

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path("markdownx/", include("markdownx.urls")),
    path("", include("portfolio.core.urls")),
    path("projects/", include("portfolio.projects.urls", namespace="projects")),
    path("blog/", include("portfolio.blog.urls", namespace="blog")),
    path("feed/rss/", LatestPostsFeed(), name="post_feed"),
    path("newsletter/", include("portfolio.newsletter.urls", namespace="newsletter")),
    path("maintenance-mode/", include("maintenance_mode.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/blog/urls.py
from django.urls import path

from .views import (
    NewPostView,
    PublishPostView,
    PostCreateView,
    PostContentEditorView,
    PostListView,
    PostDetailView,
    SecretKeyPostDetailView,
    PostDeleteView,
    PostUpdateView,
    SeriesListView,
    SeriesCreateView,
    SeriesDetailView,
    SeriesUpdateView,
    SeriesDeleteView,
    TagListView,
)

app_name = "blog"
urlpatterns = [
    path("new-post/", NewPostView.as_view(), name="new_post"),
    path("post-publish/<str:slug>/", PublishPostView.as_view(), name="post_publish"),
    path("post-list/", PostListView.as_view(), name="post_list"),
    path("post-list/<str:tag>/", PostListView.as_view(), name="post_list_filtered"),
    path("post-create/", PostCreateView.as_view(), name="post_create"),
    path(
        "post-content-editor/<str:slug>/",
        PostContentEditorView.as_view(),
        name="post_content_editor",
    ),
    path("post-detail/<str:slug>/", PostDetailView.as_view(), name="post_detail",),
    path(
        "post-secret/<str:secret_key>/",
        SecretKeyPostDetailView.as_view(),
        name="secret_post_detail",
    ),
    path("post-update/<str:slug>/", PostUpdateView.as_view(), name="post_update",),
    path("post-delete/<str:slug>/", PostDeleteView.as_view(), name="post_delete",),
    path("series-list/", SeriesListView.as_view(), name="series_list",),
    path("series-create/", SeriesCreateView.as_view(), name="series_create",),
    path(
        "series-detail/<str:slug>/", SeriesDetailView.as_view(), name="series_detail",
    ),
    path(
        "series-update/<str:slug>/", SeriesUpdateView.as_view(), name="series_update",
    ),
    path(
        "series-delete/<str:slug>/", SeriesDeleteView.as_view(), name="series_delete",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
]

portfolio/core/urls.py
from django.urls import path

from .views import home, GetInTouchView

urlpatterns = [
    path("", home, name="home"),
    path("get-in-touch/", GetInTouchView.as_view(), name="contact_me"),
]

portfolio/projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("project-create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project-details/<str:slug>/",
        ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project-update/<str:slug>/", ProjectUpdateView.as_view(), name="project_update"
    ),
    path(
        "project-delete/<str:slug>/", ProjectDeleteView.as_view(), name="project_delete"
    ),
]

portfolio/blog/models.py
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.db import models, IntegrityError, ProgrammingError, OperationalError
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from django_extensions.db.fields import AutoSlugField, RandomCharField
from django_q.tasks import Schedule, schedule
from markdownx.models import MarkdownxField
from model_utils import Choices
from model_utils.fields import MonitorField, StatusField
from model_utils.models import TimeStampedModel, SoftDeletableModel, StatusModel
from taggit.managers import TaggableManager

from portfolio.core.templatetags.core_tags import markdown
from portfolio.core.utils import get_current_domain_url
from portfolio.newsletter.models import News

User = get_user_model()


# TODO autosave content and revert changes and ctrl + s to save
class Postable(models.Model):
    thumbnail = models.OneToOneField(
        "core.Thumbnail", blank=True, null=True, on_delete=models.SET_NULL
    )
    title = models.CharField(max_length=150)
    overview = MarkdownxField()
    body = MarkdownxField(blank=True)
    slug = AutoSlugField(populate_from=["title"], max_length=120)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Post(Postable, StatusModel, TimeStampedModel, SoftDeletableModel):
    STATUS = Choices("draft", "published")
    status = StatusField(default=STATUS.draft)
    status_changed = MonitorField(monitor="status")
    publish_date = models.DateTimeField(null=True, blank=True)
    scheduled_publish_date = models.DateTimeField(null=True, blank=True)
    series = models.ForeignKey(
        "blog.Series", null=True, blank=True, on_delete=models.SET_NULL
    )
    featured = models.BooleanField(default=False)
    secret_key = RandomCharField(length=64)

    # Managers
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

    @property
    def is_published(self):
        return self.status == Post.STATUS.published

    @property
    def next_post(self):
        if not self.series:
            return None
        posts = self.series.published_post()
        if self == posts.last() or self not in posts:
            return None
        return posts[list(posts).index(self) + 1]

    @property
    def previous_post(self):
        if not self.series:
            return None
        posts = self.series.published_post()
        if self == posts.first() or self not in posts:
            return None
        return posts[list(posts).index(self) - 1]

    def publish(self):
        self.status = Post.STATUS.published
        self.publish_date = timezone.now()
        self.save()
        self.send_publish_email()

    def send_publish_email(self):
        # send email to subscribers to inform of new post
        subject = "New Post!"
        message = render_to_string(
            "blog/email/new_post_message.html",
            context={
                "title": self.title,
                "link": f"{get_current_domain_url()}{self.get_absolute_url()}",
            },
        ).format("utf-8")
        News.objects.create(subject=subject, message=message).setup()

    def create_scheduled_task(self):
        # create scheduled tast if scheduled_publish_date is set
        # ths work like newsletter.News.create_scheduled task, a placeholder task is create
        # and the hook is the one doign the real wok here using the slug of the post
        if self.is_published or not self.scheduled_publish_date:
            return
        try:
            print("here")
            schedule(
                func="blog.tasks.publish_post_task",
                name=f"{self.slug}",
                slug=self.slug,
                schedule_type=Schedule.ONCE,
                next_run=self.scheduled_publish_date,
            )
        except (ProgrammingError, IntegrityError, OperationalError):
            pass

    def save(self, *args, **kwargs):
        self.create_scheduled_task()
        super().save(*args, **kwargs)

    @property
    def sharable_url(self):
        """
        An url to reach this post (there is a secret url for sharing unpublished
        posts to outside users).
        """
        if not self.is_published:
            return reverse(
                "blog:secret_post_detail", kwargs={"secret_key": self.secret_key}
            )
        else:
            return self.get_absolute_url()

    @property
    def reading_time(self):
        word_count = len(strip_tags(markdown(self.body)).split())
        minutes = int(str(word_count / 200).split(".")[0])
        seconds = round(int(str(word_count / 200).split(".")[1]) * 0.60)
        return minutes if seconds < 30 else (minutes + 1)

    @classmethod
    def published_post(cls):
        return Post.objects.filter(status=Post.STATUS.published).order_by(
            "-publish_date"
        )


# TODO generate a body if empty
class Series(Postable, StatusModel, TimeStampedModel, SoftDeletableModel):
    STATUS = Choices("in_progress", "on_break", "finished")
    status = StatusField(default=STATUS.in_progress)
    status_changed = MonitorField(monitor="status")
    visible = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "series"

    def get_absolute_url(self):
        return reverse("blog:series_detail", kwargs={"slug": self.slug})

    def published_post(self):
        return Post.objects.filter(series=self, status=Post.STATUS.published).order_by(
            "publish_date"
        )

    def get_tags(self):
        tags = []
        for post in self.published_post():
            tags += post.tags.all()
        return tags

    @property
    def reading_time(self):
        all_posts_reading_time = [post.reading_time for post in self.published_post()]
        return sum(all_posts_reading_time)

portfolio/blog/views.py
from braces.views import SuperuserRequiredMixin, FormValidMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from taggit.models import Tag

from portfolio.newsletter.forms import SubscriptionForm
from .forms import BlogPostContentForm, PostForm, SeriesForm
from .helpers import postable_add_extra_context, post_filter
from .models import Post, Series


class NewPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/new_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        drafts = Post.objects.filter(status=Post.STATUS.draft).order_by(
            "-modified", "-created"
        )
        paginator = Paginator(drafts, 6)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class PublishPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/post_confirm_publish.html"

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        post.publish()
        messages.success(request, "Post published")
        return redirect("blog:post_list")


class PostListView(ListView):
    context_object_name = "posts"
    paginate_by = 8

    def get_queryset(self):
        queryset = Post.objects.filter(status=Post.STATUS.published).order_by(
            "-publish_date"
        )
        filtered_post = post_filter(
            self.request, tag=self.kwargs.get("tag"), queryset=queryset
        )
        return filtered_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class PostCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    model = Post
    template_name = "blog/post_create.html"
    form_class = PostForm
    form_valid_message = "Blog post created"

    def get_success_url(self) -> str:
        post = self.get_context_data().get("post")
        return reverse("blog:post_content_editor", kwargs={"slug": post.slug})


class PostContentEditorView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(initial={"body": post.body})
        return render(
            request, "blog/post_content_editor.html", {"form": form, "slug": post.slug},
        )

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(request.POST)
        if form.is_valid():
            post.body = form.cleaned_data["body"]
            post.save()
            messages.success(request, "Post Updated")
            return redirect("blog:post_detail", slug=post.slug)
        else:
            return redirect("blog:post_content_editor", kwargs={"slug": post})


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_published and not self.request.user.is_superuser:  # noqa
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SecretKeyPostDetailView(DetailView):
    model = Post
    slug_url_kwarg = "secret_key"
    slug_field = "secret_key"
    template_name = "blog/post_detail.html"

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.is_published:  # noqa
            return redirect(post.get_absolute_url())  # noqa
        return super().get(request, *args, **kwargs)


class PostUpdateView(
    SuperuserRequiredMixin, FormValidMessageMixin, UpdateView,
):
    model = Post
    template_name = "blog/post_update.html"
    form_class = PostForm
    form_valid_message = "Blog post updated"


class PostDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Post
    form_valid_message = "Blog post deleted"

    def get_success_url(self) -> str:
        return reverse("blog:post_list")


class SeriesCreateView(CreateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_create.html"


class SeriesListView(ListView):
    queryset = Series.objects.filter(visible=True).order_by("created")
    paginate_by = 8
    context_object_name = "series"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class SeriesDetailView(DetailView):
    model = Series

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SeriesUpdateView(SuperuserRequiredMixin, FormValidMessageMixin, UpdateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_update.html"
    form_valid_message = "Blog Series Updated"


class SeriesDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Series
    form_valid_message = "Blogpost Series Deleted"

    def get_success_url(self):
        return reverse("blog:series_list")


class TagListView(ListView):
    queryset = Tag.objects.all()
    template_name = "blog/tag_list.html"
    context_object_name = "tags"

portfolio/projects/views.py
from braces.views import FormValidMessageMixin, SuperuserRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from .forms import ProjectForm
from .models import Project


class ProjectListView(ListView):
    model = Project
    ordering = ["-priority", "-created"]
    paginate_by = 6
    context_object_name = "projects"


class ProjectDetailView(DetailView):
    model = Project


class ProjectCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    form_class = ProjectForm
    form_valid_message = "Project Created"
    template_name = "projects/project_create.html"


class ProjectUpdateView(FormValidMessageMixin, SuperuserRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = "projects/project_update.html"
    form_valid_message = "Project Updated"


class ProjectDeleteView(FormValidMessageMixin, SuperuserRequiredMixin, DeleteView):
    model = Project
    form_valid_message = "Project deleted"

    def get_success_url(self) -> str:
        return reverse("projects:project_list")

portfolio/templates/blog/new_post.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
  <div class="container">
    <main>
      <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">POST</h5>
              <p class="card-text">Create a new blog post.</p>
              <a href="{% url "blog:post_create" %}" class="btn btn-primary">Create</a>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Series</h5>
              <p class="card-text">Create a new series of post.</p>
              <a href="{% url "blog:series_create" %}" class="btn btn-primary">Create</a>
            </div>
          </div>
        </div>
      </div>
      <h4 class="text-center text-white mb-4 mt-4">DRAFTS</h4>
      <div class="row mb-4">
        {% for post in page_obj %}
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">{{ post.title }}</h4>
                <p class="card-text">
                  {{ blogpost.body|safe|linebreaks|truncatechars:200 }}
                </p>
                <a href="{% url "blog:post_detail" post.slug %}" class="btn btn-primary">Continue</a>
              </div>
              <div class="card-footer text-muted">
                <p>
                  Categories:
                  {% for category in post.categories.all %}
                    {{ category.name }},
                  {% endfor %}
                </p>
                <i class="icon-clock"></i> {{ post.created|naturalday }}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <!-- Pagination -->
      <nav aria-label="Page navigation example">
        <ul class="pagination pagination-template d-flex justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i
                    class="fa fa-angle-left"></i></a></li>
            <li class="page-item"><a href="?page={{ page_obj.number|add:-1 }}"
                                     class="page-link">{{ page_obj.number|add:-1 }}</a></li>
          {% endif %}
          <li class="page-item"><a href="?page={{ page_obj.number }}"
                                   class="page-link active">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.number|add:1 }}"
                                     class="page-link">{{ page_obj.number|add:1 }}</a></li>
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> <i
                    class="fa fa-angle-right"></i></a></li>
          {% endif %}
        </ul>
      </nav>
    </main>
  </div>
{% endblock %}

portfolio/templates/blog/post_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block css %}
  {{ block.super }}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
          integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock css %}


{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form | crispy }}
              <button type="submit" class="btn btn-primary">Create</button>
            </form>
            {{ form.media }}
          </div>
        </div>
      </div>
    </main>
  </div>
  <script>
    jQuery('#id_scheduled_publish_date').datetimepicker({
      format: 'm/d/Y H:i'
    });
  </script>
{% endblock %}

portfolio/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load core_tags %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block  description %}{{ post.overview|markdown|striptags }}{% endblock description %}
{% block extra_meta %}
  {% if post.thumbnail %}
    <meta property="og:image" content="{{ post.thumbnail.image.url }}"/>
    <meta name="twitter:image" content="{{ post.thumbnail.image.url }}"/>
    <meta property="og:image:width" content="{{ post.thumbnail.image.width }}"/>
    <meta property="og:image:height" content="{{ post.thumbnail.image.height }}"/>
    <meta property="og:image:alt" content="{{ post.thumbnail.alt }}"/>
  {% endif %}
  {% for tag in post.tags.all %}
    <meta property="article:tag" content="{{ tag }}"/>
  {% endfor %}
{% endblock extra_meta %}


{% block content %}

  <div class="container">
    <div class="row justify-content-center">
      <main class="col-md-10 post blog-post">
        <div class="card border-0 rounded mb-2">
          {% if post.thumbnail %}
            {% thumbnail post.thumbnail.image "1000x420" as img %}
              <img src="{{ img.url }}" alt="{{ post.thumbnail.alt }}"
                   class="card-img-top" width="{{ img.width }}" height="{{ img.height }}">
            {% endthumbnail %}
          {% endif %}
          {% if post.thumbnail.source %}
            <p class="text-muted mt-2 ml-3">(picture from: {{ post.thumbnail.source }} )</p>
          {% endif %}
          <div class="card-body">
            {% if user.is_superuser %}
              <div class="row justify-content-center mb-3">
                <div class="col-md-5">
                  <div class="btn-group btn-group-sm" role="group">
                    <button class="btn btn-outline-primary" id="sharableUrl" data-toggle="tooltip"
                            data-placement="buttom"
                            title="Copy to clipboard">Sharable Url
                    </button>
                    <a class="btn btn-outline-info" href="{% url 'blog:post_content_editor' post.slug %}">Edit
                      Content</a>
                    <a class="btn btn-outline-info" href="{% url 'blog:post_update' post.slug %}">Update</a>
                    <a class="btn btn-outline-danger" href="{% url 'blog:post_delete' post.slug %}">Delete</a>
                  </div>
                </div>
              </div>
            {% endif %}
            <h1 class="text-center">{{ post.title }}</h1>
            <div class="post-footer row justify-content-center">
              <div class="d-flex align-items-center flex-wrap">
                <div class="date"><i class="icon-clock"></i>
                  {% if post.is_published %}
                    {{ post.publish_date|timesince }}
                  {% else %}
                    {{ post.created|timesince }}
                  {% endif %} ago
                </div>
                <div class="views"><i class="icon-eye"></i> {{ post.reading_time }} minutes read</div>
                {#                <div class="comments meta-last"><i class="icon-comment"></i> {{ comment_count }} comments</div>#}
              </div>
            </div>
            <div class="post-body card">
              <div class="card-body post-detail">
                <p class="justify-content-around">{{ post.overview|markdown }}</p>
                <hr>
                <p class="text-justify">{{ post.body|markdown }}</p>
              </div>
            </div>
            <div class="post-tags">
              {% for tag in post.tags.all %}
                <a class="tag" href="{% url "blog:post_list_filtered" tag %}">#{{ tag }}</a>
              {% endfor %}
            </div>
            {% if user.is_superuser and not post.is_published %}
              <a href="{% url "blog:post_publish" post.slug %}"
                 class="btn btn-outline-primary btn-block mt-2">Publish</a>
            {% endif %}
            <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
              {% if post.previous_post %}
                <a href="{{ post.previous_post.get_absolute_url }}"
                   class="prev-post text-left d-flex align-items-center">
                  <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                  <div class="text"><strong class="text-primary">Previous Post </strong>
                    <h6>{{ post.previous_post.title }}</h6>
                  </div>
                </a>
              {% endif %}
              {% if post.next_post %}
                <a href="{{ post.next_post.get_absolute_url }}"
                   class="next-post text-right d-flex align-items-center justify-content-end">
                  <div class="text"><strong class="text-primary">Next Post </strong>
                    <h6>{{ post.next_post.title }}</h6>
                  </div>
                  <div class="icon next"><i class="fa fa-angle-right"> </i></div>
                </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card card-body mb-2">
          <!-- TODO try to use the github api to fetch comment counts -->
          <details>
            <summary class="mb-3">Show comments</summary>
            <script src="https://utteranc.es/client.js"
                    repo="Tobi-De/Tobi-De"
                    issue-term="title"
                    label="Blog"
                    theme="github-light"
                    crossorigin="anonymous"
                    async>
            </script>
          </details>
        </div>
        {% include "newsletter.html" with n_form=newsletter_form %}
      </main>
    </div>
  </div>
  <script>
    var copySharableUrlBtn = document.querySelector('#sharableUrl');
    copySharableUrlBtn.addEventListener('click', function (event) {
      // Select the email link anchor text
      const el = document.createElement('textarea');
      el.value = "{{ post.sharable_url|abs_url:request }}";
      el.setAttribute('readonly', '');
      el.style.position = 'absolute';
      el.style.left = '-9999px';
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
    });
  </script>
{% endblock %}

portfolio/templates/blog/series_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load core_tags %}

{% block description %} Series of articles about django, python and web development in
  general.{% endblock description %}

{% block content %}
  <div class="container">
    <div class="row">
      {% include "sidebar_left.html" %}
      <main class="posts-listing col-md-6">
        {% if page_obj %}
          {% for series in page_obj %}
            <div class="post card border-0">
              {% if series.thumbnail %}
                {% thumbnail series.thumbnail.image "653x277" as img %}
                  <img src="{{ img.url }}" alt="{{ series.thumbnail.alt }}"
                       width="{{ img.width }}" height="{{ img.height }}" class="img-fluid">
                {% endthumbnail %}
              {% endif %}
              <div class="post-meta ml-3 d-flex justify-content-between">
                <div class="category">
                  {% for tag in series.get_tags %}
                    <a href="{% url "blog:post_list_filtered" tag %}">#{{ tag }}</a>
                  {% endfor %}
                </div>
              </div>
              <a href="{{ series.get_absolute_url }}">
                <h3 class="text-center">{{ series.title }}</h3>
              </a>
              <div class="card-body">
                <p>{{ series.overview|markdown }}</p>
                <footer class="post-footer row justify-content-center">
                  <div class="date"><i class="icon-clock"></i> {{ series.created|timesince }} ago</div>
                  <div class="views"><i class="icon-eye"></i> {{ series.reading_time }} minutes read</div>
                </footer>
              </div>
            </div>
          {% endfor %}
          <!-- Pagination -->
          <nav aria-label="Page navigation">
            <ul class="pagination pagination-template d-flex justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> <i
                        class="fa fa-angle-left"></i></a></li>
                <li class="page-item"><a href="?page={{ page_obj.number|add:-1 }}"
                                         class="page-link">{{ page_obj.number|add:-1 }}</a></li>
              {% endif %}
              <li class="page-item"><a href="?page={{ page_obj.number }}"
                                       class="page-link active">{{ page_obj.number }}</a></li>
              {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.number|add:1 }}"
                                         class="page-link">{{ page_obj.number|add:1 }}</a></li>
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> <i
                        class="fa fa-angle-right"></i></a></li>
              {% endif %}
            </ul>
          </nav>
        {% else %}
          <div class="card-body bg-white mr-3 rounded">
            <p class="text-center h4">
              Sorry nothing found
              <img class="center"
                   src="https://img.icons8.com/ios-glyphs/60/000000/nothing-found.png"
                   alt=";("/>
            </p>
          </div>
        {% endif %}
      </main>
      {% include "sidebar_right.html" with form=newsletter_form %}
    </div>
  </div>
{% endblock %}