config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token
from portfolio.blog.feeds import LatestPostsFeed

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path("markdownx/", include("markdownx.urls")),
    path("", include("portfolio.core.urls")),
    path("projects/", include("portfolio.projects.urls", namespace="projects")),
    path("blog/", include("portfolio.blog.urls", namespace="blog")),
    path("feed/rss/", LatestPostsFeed(), name="post_feed"),
    path("newsletter/", include("portfolio.newsletter.urls", namespace="newsletter")),
    path("maintenance-mode/", include("maintenance_mode.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

portfolio/blog/urls.py
from django.urls import path

from .views import (
    NewPostView,
    PublishPostView,
    PostCreateView,
    PostContentEditorView,
    PostListView,
    PostDetailView,
    SecretKeyPostDetailView,
    PostDeleteView,
    PostUpdateView,
    SeriesListView,
    SeriesCreateView,
    SeriesDetailView,
    SeriesUpdateView,
    SeriesDeleteView,
    TagListView,
)

app_name = "blog"
urlpatterns = [
    path("new-post/", NewPostView.as_view(), name="new_post"),
    path("post-publish/<str:slug>/", PublishPostView.as_view(), name="post_publish"),
    path("post-list/", PostListView.as_view(), name="post_list"),
    path("post-list/<str:tag>/", PostListView.as_view(), name="post_list_filtered"),
    path("post-create/", PostCreateView.as_view(), name="post_create"),
    path(
        "post-content-editor/<str:slug>/",
        PostContentEditorView.as_view(),
        name="post_content_editor",
    ),
    path("post-detail/<str:slug>/", PostDetailView.as_view(), name="post_detail",),
    path(
        "post-secret/<str:secret_key>/",
        SecretKeyPostDetailView.as_view(),
        name="secret_post_detail",
    ),
    path("post-update/<str:slug>/", PostUpdateView.as_view(), name="post_update",),
    path("post-delete/<str:slug>/", PostDeleteView.as_view(), name="post_delete",),
    path("series-list/", SeriesListView.as_view(), name="series_list",),
    path("series-create/", SeriesCreateView.as_view(), name="series_create",),
    path(
        "series-detail/<str:slug>/", SeriesDetailView.as_view(), name="series_detail",
    ),
    path(
        "series-update/<str:slug>/", SeriesUpdateView.as_view(), name="series_update",
    ),
    path(
        "series-delete/<str:slug>/", SeriesDeleteView.as_view(), name="series_delete",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
]

portfolio/core/urls.py
from django.urls import path

from .views import home, GetInTouchView

urlpatterns = [
    path("", home, name="home"),
    path("get-in-touch/", GetInTouchView.as_view(), name="contact_me"),
]

portfolio/newsletter/urls.py
from django.urls import path

from .views import (
    SubscriptionView,
    SubscribeConfirmView,
    UnsubscribeView,
    SendNews,
    UnsubscribeConfirmView,
    SendUnsubscribeLinkView,
)

app_name = "newsletter"
urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path(
        "subscribe-confirm/<str:uuid>/",
        SubscribeConfirmView.as_view(),
        name="subscribe_confirm",
    ),
    path("unsubscribe/<str:uuid>/", UnsubscribeView.as_view(), name="unsubscribe"),
    path(
        "unsubscribe-confirm/",
        UnsubscribeConfirmView.as_view(),
        name="unsubscribe_confirm",
    ),
    path(
        "unsubscribe-test/", SendUnsubscribeLinkView.as_view(), name="unsubscribe_test",
    ),
    path("send-news/", SendNews.as_view(), name="send_news"),
]

portfolio/projects/urls.py
from django.urls import path

from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)

app_name = "projects"
urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("project-create/", ProjectCreateView.as_view(), name="project_create"),
    path(
        "project-details/<str:slug>/",
        ProjectDetailView.as_view(),
        name="project_detail",
    ),
    path(
        "project-update/<str:slug>/", ProjectUpdateView.as_view(), name="project_update"
    ),
    path(
        "project-delete/<str:slug>/", ProjectDeleteView.as_view(), name="project_delete"
    ),
]

portfolio/newsletter/models.py
import re

from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.db import models, ProgrammingError, IntegrityError, OperationalError
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django_extensions.db.fields import RandomCharField
from django_extensions.db.fields import ShortUUIDField
from django_q.tasks import async_task, Schedule, schedule
from markdownx.models import MarkdownxField
from model_utils.models import TimeStampedModel

from core.templatetags.core_tags import markdown
from core.utils import get_current_domain_url

User = get_user_model()


# TODO send a recap of blog posts every month end


class Subscriber(TimeStampedModel):
    email = models.EmailField(unique=True)
    uuid = ShortUUIDField()
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.email

    def is_email_valid(self):
        email_pattern = re.compile(r"^([\w\-.]+)@([\w\-.]+)\.([a-zA-Z]{2,5})$")
        return email_pattern.fullmatch(self.email)

    def confirm(self):
        if not self.confirmed:
            self.confirmed = True
            self.save()
            self.send_welcome_mail()

    @classmethod
    def add_subscriber(cls, email):
        sub = Subscriber(email=email)
        sub.save()
        sub.send_confirmation_mail()

    @classmethod
    def remove_subscriber(cls, sub_obj, title, message, **kwargs):
        subject = "Somebody Unsubscribed"
        _message = f"Email :{sub_obj.email}\nTitle: {title}\nMessage: {message}"
        send_mail(
            subject=subject,
            message=_message,
            from_email=None,
            recipient_list=["contact@tobidegnon.com"],
        )
        sub_obj.delete()

    def get_confirmation_link(self):
        return f"{get_current_domain_url()}{reverse('newsletter:subscribe_confirm', kwargs={'uuid': self.uuid})}"

    def get_unsubscribe_link(self):
        return f"{get_current_domain_url()}{reverse('newsletter:unsubscribe', kwargs={'uuid': self.uuid})}"

    def send_welcome_mail(self):
        message = render_to_string("newsletter/email/welcome_message.txt",).format(
            "utf-8"
        )
        async_task(
            send_mail,
            subject="Welcome!",
            message=message,
            from_email=None,
            recipient_list=[self.email],
            html_message=render_to_string("newsletter/email/welcome_message.html",),
        )

    def send_confirmation_mail(self):
        message = render_to_string(
            "newsletter/email/confirmation_message.txt",
            context={"link": self.get_confirmation_link()},
        ).format("utf-8")
        async_task(
            send_mail,
            subject="Confirm Email",
            message=message,
            from_email=None,
            recipient_list=[self.email],
            html_message=render_to_string(
                "newsletter/email/confirmation_message.html",
                {"link": self.get_confirmation_link()},
            ),
        )

    # for testing purpose
    def send_unsubscription_link(self):
        subject = "Unsubscribe"
        message = f"Unsubscription link {self.get_unsubscribe_link()}"
        async_task(
            send_mail,
            subject=subject,
            message=message,
            from_email=None,
            recipient_list=[self.email],
        )

    @classmethod
    def emailable_subscribers(cls):
        return Subscriber.objects.filter(confirmed=True).order_by("-created")


class News(TimeStampedModel):
    subject = models.CharField(max_length=60)
    message = MarkdownxField()
    key_identifier = RandomCharField(length=32)
    dispatch_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "news"

    def __str(self):
        return self.subject

    def get_mail_content(self, subscriber):
        marked_content = markdown(self.message)
        message = strip_tags(
            f"{marked_content}\n\nYou can unsubscribe to this newsletter at anytime"
            f" via this link {subscriber.get_unsubscribe_link()}."
        )
        html_message = (
            f"{marked_content}\n\nYou can "
            f"<a href='{subscriber.get_unsubscribe_link()}'>unsubscribe</a> to this newsletter at anytime."
        )
        return {
            "subject": self.subject,
            "message": strip_tags(message),
            "from_email": None,
            "recipient_list": [subscriber.email],
            "html_message": html_message,
        }

    def create_scheduled_task(self):
        try:
            schedule(
                func="newsletter.tasks.send_news_task",
                key_identifier=self.key_identifier,
                schedule_type=Schedule.ONCE,
                next_run=self.dispatch_date,
            )
        except (ProgrammingError, IntegrityError, OperationalError):
            pass

    def setup(self):
        if self.dispatch_date:
            self.create_scheduled_task()
        else:
            self.send()

    def send(self):
        if Subscriber.emailable_subscribers().count() == 0:
            return
        self.async_mass_mailing(news_object=self)

    @classmethod
    def async_mass_mailing(cls, news_object, offset=0, limit=100):
        if Subscriber.emailable_subscribers()[offset:].count() <= 0:
            return
        for sub in Subscriber.emailable_subscribers()[offset : offset + limit]:
            send_mail(**news_object.get_mail_content(subscriber=sub))
        async_task(
            News.async_mass_mailing,
            news_object=news_object,
            offset=offset + limit,
            limit=limit,
        )

portfolio/projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = [
            "carousel",
            "title",
            "description",
            "status",
            "what_ive_learned",
            "tech_stack",
            "featured",
            "priority",
            "github_link",
            "web_link",
        ]

portfolio/blog/views.py
from braces.views import SuperuserRequiredMixin, FormValidMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import (
    View,
    TemplateView,
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from taggit.models import Tag

from portfolio.newsletter.forms import SubscriptionForm
from .forms import BlogPostContentForm, PostForm, SeriesForm
from .helpers import postable_add_extra_context, post_filter
from .models import Post, Series


class NewPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/new_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        drafts = Post.objects.filter(status=Post.STATUS.draft).order_by(
            "-modified", "-created"
        )
        paginator = Paginator(drafts, 6)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["page_obj"] = page_obj
        return context


class PublishPostView(SuperuserRequiredMixin, TemplateView):
    template_name = "blog/post_confirm_publish.html"

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        post.publish()
        messages.success(request, "Post published")
        return redirect("blog:post_list")


class PostListView(ListView):
    context_object_name = "posts"
    paginate_by = 8

    def get_queryset(self):
        queryset = Post.objects.filter(status=Post.STATUS.published).order_by(
            "-publish_date"
        )
        filtered_post = post_filter(
            self.request, tag=self.kwargs.get("tag"), queryset=queryset
        )
        return filtered_post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class PostCreateView(FormValidMessageMixin, SuperuserRequiredMixin, CreateView):
    model = Post
    template_name = "blog/post_create.html"
    form_class = PostForm
    form_valid_message = "Blog post created"

    def get_success_url(self) -> str:
        post = self.get_context_data().get("post")
        return reverse("blog:post_content_editor", kwargs={"slug": post.slug})


class PostContentEditorView(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(initial={"body": post.body})
        return render(
            request, "blog/post_content_editor.html", {"form": form, "slug": post.slug},
        )

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs.get("slug"))
        form = BlogPostContentForm(request.POST)
        if form.is_valid():
            post.body = form.cleaned_data["body"]
            post.save()
            messages.success(request, "Post Updated")
            return redirect("blog:post_detail", slug=post.slug)
        else:
            return redirect("blog:post_content_editor", kwargs={"slug": post})


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_published and not self.request.user.is_superuser:  # noqa
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SecretKeyPostDetailView(DetailView):
    model = Post
    slug_url_kwarg = "secret_key"
    slug_field = "secret_key"
    template_name = "blog/post_detail.html"

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if post.is_published:  # noqa
            return redirect(post.get_absolute_url())  # noqa
        return super().get(request, *args, **kwargs)


class PostUpdateView(
    SuperuserRequiredMixin, FormValidMessageMixin, UpdateView,
):
    model = Post
    template_name = "blog/post_update.html"
    form_class = PostForm
    form_valid_message = "Blog post updated"


class PostDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Post
    form_valid_message = "Blog post deleted"

    def get_success_url(self) -> str:
        return reverse("blog:post_list")


class SeriesCreateView(CreateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_create.html"


class SeriesListView(ListView):
    queryset = Series.objects.filter(visible=True).order_by("created")
    paginate_by = 8
    context_object_name = "series"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        postable_add_extra_context(context=context)
        return context


class SeriesDetailView(DetailView):
    model = Series

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["newsletter_form"] = SubscriptionForm()
        return context


class SeriesUpdateView(SuperuserRequiredMixin, FormValidMessageMixin, UpdateView):
    model = Series
    form_class = SeriesForm
    template_name = "blog/series_update.html"
    form_valid_message = "Blog Series Updated"


class SeriesDeleteView(SuperuserRequiredMixin, FormValidMessageMixin, DeleteView):
    model = Series
    form_valid_message = "Blogpost Series Deleted"

    def get_success_url(self):
        return reverse("blog:series_list")


class TagListView(ListView):
    queryset = Tag.objects.all()
    template_name = "blog/tag_list.html"
    context_object_name = "tags"

portfolio/templates/newsletter/send_news.html
{% extends "base.html" %}
{% load crispy_forms_tags static %}


{% block css %}
  {{ block.super }}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
          integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
{% endblock css %}


{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="card col-md-10">
        <div class="card-body">
          <h4>Send News</h4>
          <form method="post" class="mt-4">
            {% csrf_token %}
            {{ form |crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          {{ form.media }}
        </div>
      </div>
    </main>
  </div>
  <script>
    jQuery('#id_dispatch_date').datetimepicker({
      format: 'm/d/Y H:i'
    });
  </script>
{% endblock %}

portfolio/templates/newsletter/submission.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <main>
      <div class="card">
        <div class="card-body">
          {% if is_valid %}
            <h4>Almost done.</h4>
            <p>
              We need to confirm the email address {{ email }} is actualy yours.
              To complete the subscription process, please click the link in the email we just sent you.
              If you didn't receive the email, please check your spam folder.</p>
            <div class="btn-group">
              <a class="btn btn-secondary" href="{% url "blog:post_list" %}">Back</a>
            </div>
            </div>
          {% else %}
            <h4>Oops somethings wrent wrong !</h4>
            <p>
              Seems your email address is invalid (Or already subscribed), try again please.
              If the issue persist please <a href="mailto:contact@tobidegnon.com">contact us</a>.</p>
            <form method="post" action="{% url "newsletter:submission" %}">
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
          {% endif %}
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/subscribe.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            {% if is_valid %}
              <h4>Almost done.</h4>
              <p>
                We need to confirm the email address {{ email }} is actualy yours.
                To complete the subscription process, please click the link in the email we just sent you.
                If you didn't receive the email, please check your spam folder.</p>
              <div class="btn-group">
                <a class="btn btn-secondary" href="{% url "blog:post_list" %}">Back</a>
              </div>
            {% else %}
              <h4>Oops somethings wrent wrong !</h4>
              <p>
                Seems your email address is invalid (Or already subscribed), try again please.
                If the issue persist please <a href="mailto:contact@tobidegnon.com">contact us</a>.</p>
              <form method="post" action="{% url "newsletter:subscribe" %}">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            {% endif %}
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/subscribe_confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h4>Subscription Confirmed</h4>
            <p>Thanks for joining my newsletter, your email is now confirmed.</p>
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/subscription_confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main>
      <div class="card">
        <div class="card-body">
          <p>Thanks for joining my newsletters, your email is now confirmed</p>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/thank_for_subscription.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main>
      <div class="card">
        <div class="card-body">

        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/unsubscribe.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h4>Unsubscribe</h4>
            <p>I'm sad to see you leave, can you please fill out this to form to explain why you decide to unsubscribe
              to
              my
              newsletter.</p>
            <form method="post">
              {% csrf_token %}
              {{ form | crispy }}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/unsubscribe_confirm.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h4>Unsubscribe</h4>
            <p>You are now unsubscribe.</p>
            <div class="btn-group">
              <a class="btn btn-secondary" href="{% url "blog:post_list" %}">Back</a>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/unsubscribe_confirmation.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <main>
      <div class="card">
        <div class="card-body">
          <p>You are now unsubscribe</p>
        </div>
      </div>
    </main>
  </div>
{% endblock %}

portfolio/templates/newsletter/unsubscribe_test.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <main class="row justify-content-center">
      <div class="col-md-10">
        <div class="card">
          <div class="card-body">
            <h4>Unsubscribe Test</h4>
            <form method="post">
              {% csrf_token %}
              {{ form | crispy }}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </main>
  </div>
{% endblock %}